changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## dbt-fusion {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: "### {{.Kind}}"
changeFormat: |-
  - {{.Body}}{{if .Custom.PR}} ({{.Custom.PR}}){{end}}{{if .Custom.Issues}} - {{.Custom.Issues}}{{end}}

kinds:
  - label: Breaking Changes
  - label: Features
  - label: Fixes
  - label: Under the Hood
  - label: Dependencies
  - label: Security

newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1
