name: Typos Check
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ${{ vars.UBUNTU_RUNNER }}
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master
      with:
        config: ./_typos.toml
