[package]
name = "vortex-client"
version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true

[dependencies]
proto-rust = { path = "../proto-rust" }

# client dependencies
dbt-env = { workspace = true }
http = { workspace = true }
log = { workspace = true }
pbjson-types = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }
uuid = { workspace = true }

[lib]
name = "vortex_client"
path = "src/lib.rs"
doctest = false
