// DO NOT EDIT!!!
// This file is generated by cargo run --bin xdbc-sync

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 109] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.7"),
        "d13dd1e196fdb281e069a4ddb11c00fc8a631d2f8ccc0d7e1259585dd322f4a8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "b52f005523f09db5df8e59818f1775364d59086d96f42e0fe79b5a2d13f4d99b",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "ec2d400ed5cc868150aba4d2b995964cc821bb413d697f81bf5e2c358caca31e",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.7"),
        "1f04dd3ac174061e2a1c1a7a004cc3007fbfac967ef9dab262e1c750bb4510c7",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "346f3a916575f08bdba98d6dd6bc69df5d70d197e614cca25213ec839a4bb1b4",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "7015f7c515997ff666bbe3d96d62dd0da39824177dc9bc69155a989a500eed4d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.7"),
        "78852480c7c95d7f01937b590510b9ea4b2296b5678c8374d0d1e5c16b6d1fc6",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "06723a3dc1ff519e952fb9844fd00ee75d414ca79da135207b96bbfd842cfabb",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "288009c1fd5c18ec9a54cfd7c7223179151d3fc57832f77d0c069220cbcc008b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.7"),
        "be650f3c507000db77d2fd06e88e4c000c112ba931464b9fdf23104cfaef05b5",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "9d1ff67cde78b73bd5cc28b2f5ab4b853c3b4b598d99f7c9f1140b8111bf126b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "36b9e54aa4ee5df0ebadb66f1635daa9736dc3173794762c09da401b5d9f177f",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.7"),
        "584b55e90ec6eb9e7355f367c66de4fc2d0df9a7302caedb0263cb767e20a710",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "ecf0127dfcc50f2917fbff4de9022f370b2f1caf44ab75ea01846d4a81990e60",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "4aaf192f26f791ab58850ff357235717245963e9e83401246ac72b54771517a3",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "09d79701b729a52854862ba34f8756ae93f1f45a8ba33dd8300194beb5adca14",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "56528db01bce2834d601acb45fe2b6f0ed1e80b7856078fb51f769c1459591ec",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.7"),
        "2aba2e95e2d5110f03bfbacd24a873ff94335f56e09e86ec04453151c499a1b6",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "4b38c2b39a41c057d021e2a5f558e316bcaa9b5b1ef41468398fee51958e801b",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "fcc269a403eb936bbf2a26936c7e7c61e8d05370cb087834838ab9eee6a380d4",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.7"),
        "fa06f6e8570f5b5ca65d1d653b157c9fbd8124fc8f3df1f9e1da1ab242deb33f",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "8f497697b5fe676f07d7a79e4539307c2e145458aafc67ad812a915bb44bbaaf",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "da993d20451662c41c21aea0b878b296532a30fe5d92db34f0ffc7179a6c369c",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.7"),
        "7cdccf45953ad72fc1285d286e52778ece6cb8949d56de43a418f59cde14d858",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "bafc65d554eb39614c9878cf66b07c11b578dec895923ca2f5b08261d8171219",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "37a4ba937d9aea99581ebca6b9e418121c4cc81e02f6273d7aa8022121d6854d",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.7"),
        "84e15ef3c5305431d34c84588aba10f4f68d8bbda2adcd157a2d18f39fe71434",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "73cce7c25c517f3b75be60c908e447d385aeab0f28a17107319a5b1763c64c02",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "e6ec384ae6a106208674f6aa3381baad64207c89da46560a6dfae5ec20d9b9cb",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.7"),
        "5d70ef5a470adf499e8aba40423123ce15df16c050012e16f1511c92091ec712",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.5"),
        "63056e2f2430ec3b12d9bbe46d237409a1e17f583819ad1a7d17c208d79931cc",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.6"),
        "ee73023c77b3044568603530cf8706997eed1d64a5b8be6e861e15bf17759b9d",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.7"),
        "1e9dbb315a77907d3634f65c6f32f561caa566cd9481c04668ad919de6ac0e02",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.9"),
        "2ce4808291197ee793e0726507bc859db15115a1dd900a7f232cf4c944e7976b",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.5"),
        "03c0f2116684e11d65183212262703288e2c9467b20420000aa4a161cea427b7",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.6"),
        "bc4b2d3ce596d5763346085a830f76dfb674aea549326175e7ac4bc9d8d5f183",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.7"),
        "2a0a2902f09ea05c81745d06ee5e6a9d35600247d76f18a924abb37b11aca309",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.9"),
        "94e14a9a641feec945d51efaeb66ea883902dd37c7da1c628c0b5eeb45a97885",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.5"),
        "3157c1834f8be2fd0ca02fe9e618e8ce10115b4d53a8b12331011edddcabd758",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.6"),
        "a44691ada1db5f9216701deb855a10ffd20087fe3e6f9af56675dfb1622214e6",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.7"),
        "1c62f3c08af0ee4d650b8505848c9c858c9c51052a72c34ebfe40a53f633e96f",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.9"),
        "2c26036adcf22f65e00753a01ead5b5dbb1edabc93c116bd9a33e9a070301b4d",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.5"),
        "b51aff4fbd7167d56fb0572cd8611756e9aba8d9cf4ab1df870fb72e32292bdd",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.6"),
        "3567dc832c4b96b267994c65bc095f2a426c4c35c9aa7083c1c372c88049ca9e",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.7"),
        "44570570c6f878237a1c40c00b99092a089d6efcc54ea288fbd487a7d64c1be5",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.9"),
        "83604a6be3c2ed9c8ba30a31b0be275241cccbae484a9385c8126680cff242d6",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.5"),
        "70d5af8fe22529ebf2e46ce75a658e9e52b4d4bcafff36e8415681c1326c4603",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.6"),
        "e1d5946cf947bedfe4ef1a3e178366f6a5ddba690c4348d2c9df900ecc37c964",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.7"),
        "102357f1617e5c4279641a1b0af5b83386c3299563bc02d9a4a96b2d78fae37d",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.9"),
        "b20219041f2012d3ec7aa25d5eac8e2abc94ac4a3489bdc63d187486155d02ba",
    ),
    (
        ("mssql", "apple-darwin", "aarch64", "1.3.1"),
        "7e356f8f2f89a89b7a5c45fc255e8c5429f934b634e6071c689fad323a0f0de4",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "aarch64", "1.3.1"),
        "cb3f81b8a220fb5659f1f9d3516b8cb15742326fb900df01b18cb68bb0dd0e96",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "x86_64", "1.3.1"),
        "8714af2a435e4de896192fa89336dde1461ff127fd1375b07be33a8da4e7da30",
    ),
    (
        ("mssql", "pc-windows-msvc", "x86_64", "1.3.1"),
        "bcb6b0235297c0797e0cd0999fe1cf79d35c6b45e4abf33b9cae0252fc2a8cd3",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "07afc8277fd952d956b7de7a8129b323dad9a1aea71e35e3a0d31dee6371546d",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "cca3bb3f50a93879a346b50fb49374ced4494f65796ccd60e933c841eea3f27f",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "279f5b9f042a7729f33c053e675f6d0c530a9ce8b88fa6965a981bd93a939df8",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "cbc2a0865bfc311663db2c2564830e4d4d260beda29baecd4371d8ce52eada5b",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "4986f51e67888f77999525301386505f6375edcb36af4018becff374bb3f82e2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0+dbt0.21.1"),
        "a651b99de9f3d4987259735f9d4bd45c965edd76d46f7b8a1126e1ada07257ab",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "7398485ff259430a72b494a0748def1008b73b8f6f8f44a3f8e69e07e595f7e8",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0+dbt0.21.1"),
        "06daae1581f75f8bf4d26fed1baf880d7ef31deeb0e15b5d6e90090e447831cc",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "9bea90938356fde1fd6f45328acc8d4195d65a99d5f0691a0589b22eefc6a5c4",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.1"),
        "c77793e9b83963d144a250bcec207dbec598b653eed077f4fae95e59959472c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "bc67fe4e18559d9cf32b7a70606062dde549048aeb3891043cfcc359beeeddf6",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.1"),
        "6833d78af651a22cd81e8e6b1a67cf5e263ff15cbf116a3292f5558f9cdad696",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "a4164521066952ea7e49429dec0ce416d28504085d1b136e7e1fdb52d1f80c4d",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.1"),
        "4226fa0ed53848b61647f1bdf5b914bae7a033f44dc5bd84622f6d900c1f32f8",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "62266aef59e70e22ce293a6bc1accd24f09c0eb2283fb24c00bdf6e92213a28d",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "499ca4757242586134dc5a09d07f6359dfd54ad637b20e497765042c71240708",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "f1046c0d80782130aeb678d56d1a2110b8abe057403e4b4bb22b4e497967cd99",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "2373e633158e743e3df33ec7b79816f25c252be936e834a8e49400dd51c9f19e",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "006c885c1d5a7ab524df40786fdd86e0b19a0288eb902a570794f2d5ffb5c213",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "a29e533233009fef21bccb93950b338e41806536d84ed5b6b42e657fcafb9999",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "440fe53cfe8b4fb7d1f2e407b28e64a0da2b8c5c20bd26e5290c031ffb703b9f",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "60212a57ec83687b8db4e5aeddda59b4f472b97518ba34322c4d3e8e64d14172",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "e85d0cac4f9a890d68cfa5f75ae655f39fb08b578613ed12c282f7e023c6c137",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "896042c7f2d8ffc82093a79239a1adaa938e436952088fe369b86ccfdd04a79a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "9cfd75f1a386354050da8d248b6726719f65328f9594d6102593b5cff71353dc",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b6c5434bea75b3a1da5d4f9598de93384d316c44e6fcd21d8b2dd8b3dfad93de",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "347b18c1cc2fb82a22e3b51cb5d8f1165991cfc5eccf147f1baea3e1ddb7fb67",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b653fd0fe587e46f71375ce6927b81385c706dc80af98b9ab19b82799119f91b",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "3712e4d8dd9938c22e070f66bafb7757e67ce8a29c13de57bf17c214013a13dc",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "ee8d81104889a3e7a0324e108bc41a0a38e724806b92136e2c38f96e5ee7ca93",
    ),
];
