name: Copybara - Auto Public PR Migration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - '**/dbt-parser/src/resolver.rs'

permissions:
  contents: read
  packages: read

jobs:

  copybara:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/dbt-labs/fs-cli-copybara:latest
        credentials:
          username: fa-assistant
          password: ${{ secrets.FA_ASSISTANT_CI_WORKFLOW_PAT_TOKEN }}
      steps:
        - name: Public PR Copybara Trigger
          run: |    
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.FA_ASSISTANT_CI_WORKFLOW_PAT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/dbt-labs/fs/dispatches \
              -d "{\"event_type\": \"public-pr-copybara-trigger\", \"client_payload\": {\"copybara_pr\": \"${{ github.event.number }}\", \"unit\": false, \"integration\": true}}"
