# **what?**
# Since we don't merge most PRs in this repo, we need 
# a visible way to enforce branch protections to ensure
# changes can be properly merged and deployed.

# **why?**
# For security hardening.

# **when?**
# This will run for all PRs targetting main.


name: Enforce Branch Protections

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: write

env:
  SIGNED_COMMITS_COMMENT: >
    This repository enforces signed commits. Please sign your commits by following the docs [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

jobs:
  enforce_signed_commits:
    runs-on: ubuntu-latest
    steps:
      - name: "Check commit signatures"
        id: signed-commits
        shell: bash
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get list of commits in PR and check their verification status
          if gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" | \
             jq -e '.[] | select(.commit.verification.verified != true)' > /dev/null; then
            echo "Found unsigned commits"
            echo "signed-commits=false" >> $GITHUB_OUTPUT
            gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" | \
              jq -r '.[] | select(.commit.verification.verified != true) | "SHA: \(.sha)\nMessage: \(.commit.message)\nReason: \(.commit.verification.reason)\n"'
          else
            echo "All commits are signed"
            echo "signed-commits=true" >> $GITHUB_OUTPUT
          fi

      - name: "Check for comment"
        if: steps.signed-commits.outputs.signed-commits == 'false'
        id: signed_comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
        with:
            issue-number: ${{ github.event.pull_request.number }}
            comment-author: "github-actions[bot]"
            body-includes: ${{ env.SIGNED_COMMITS_COMMENT }}

      - name: "Set if comment already exists"
        if: steps.signed-commits.outputs.signed-commits == 'false'
        shell: bash
        id: comment_check
        run: |
            if [ '${{ steps.signed_comment.outputs.comment-body }}' = '' ]; then
                echo "exists=false" >> $GITHUB_OUTPUT
                echo "Comment does not exist for this PR"
            else
                echo "exists=true" >> $GITHUB_OUTPUT
                echo "Comment already exists for this PR"
            fi

      - name: "Create PR comment if signed commits are missing"
        if: |
            steps.signed-commits.outputs.signed-commits == 'false' &&
            steps.comment_check.outputs.exists == 'false'
        run: |
            gh issue comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "${{ env.SIGNED_COMMITS_COMMENT }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Fail job if signed commits are missing"
        if: steps.signed-commits.outputs.signed-commits == 'false'
        uses: actions/github-script@v7
        with:
            script: core.setFailed('Signed commits are required to merge.')
