name: FS Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  # Incremental builds only increase overhead in CI environment:
  CARGO_INCREMENTAL: 0
  CONTINUOUS_INTEGRATION: "yes"

permissions:
  contents: read
  packages: read

# Cancel previous PR builds.
concurrency:
  # For a PR build, only pr_number is filled in, triggering cancellation of previous PR builds.
  # For a push (to an enabled branch), SHA and branch name are filled in.
  # For a workflow dispatch, cancellation is based on the commit SHA and dispatch parameters.
  # The names are abbreviated to keep total output under 400 character limit
  group: >-
    wf=${{ github.workflow }},
    pr=${{ github.event_name == 'pull_request' && github.event.number || 'NA' }},
    br=${{ github.event_name == 'push' && github.sha || 'NA' }},
    br=${{ github.event_name == 'push' && github.ref_name || 'NA' }},
    di=${{ github.event_name == 'repository_dispatch' && github.sha || 'NA' }},
  cancel-in-progress: true

jobs:

  test_fs:
    name: "Test Fusion"
    needs: [check_changes]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/fs-cli-x86_64:latest-with-datasets
      credentials:
        username: fa-assistant
        password: ${{ secrets.FA_ASSISTANT_CI_WORKFLOW_PAT_TOKEN }}
    steps:
      - name: Configure GitHub auth via ~/.netrc
        run: |
          cat > ~/.netrc <<EOF
          machine github.com
            login fa-assistant
            password ${{ secrets.FA_ASSISTANT_CI_WORKFLOW_PAT_TOKEN }}
          EOF

      - name: Test Fusion
        uses: actions/checkout@v4
        run: |
          RUST_MIN_STACK="8388608" cargo nextest run

      
